[package]
name = "synchron"
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.5"
dbus-crossroads = "0.5.0"
expanduser = "1.2.2"
gstreamer = "0.17.4"
gstreamer-player = "0.17.0"
id3 = "0.6.6"
scanln = "0.1.1"
